version: "3.8"
services:
  postgres:
    container_name: postgres-container
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mark_one_db
    restart: always

volumes:
  postgres:
